# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('scheduler', '0001_initial'), ('scheduler', '0002_auto_20160423_2351'), ('scheduler', '0003_auto_20160423_2358'), ('scheduler', '0004_auto_20160424_2047'), ('scheduler', '0005_auto_20160425_1223'), ('scheduler', '0006_auto_20160425_1223'), ('scheduler', '0007_auto_20160425_1229'), ('scheduler', '0008_auto_20160425_1508'), ('scheduler', '0009_auto_20160425_1529'), ('scheduler', '0010_auto_20160427_1049'), ('scheduler', '0011_auto_20160427_1104'), ('scheduler', '0012_auto_20160427_1111'), ('scheduler', '0013_auto_20160427_1117'), ('scheduler', '0014_auto_20160428_1245'), ('scheduler', '0015_auto_20160428_2301'), ('scheduler', '0016_auto_20160430_1706'), ('scheduler', '0017_auto_20160430_1707'), ('scheduler', '0018_auto_20160430_1940'), ('scheduler', '0019_event_event_id'), ('scheduler', '0020_auto_20160430_1942'), ('scheduler', '0021_auto_20160430_1948'), ('scheduler', '0022_auto_20160430_2005'), ('scheduler', '0023_remove_event_start_datetime'), ('scheduler', '0024_event_start_datetime'), ('scheduler', '0025_auto_20160430_2202')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(verbose_name='start datetime')),
                ('duration', models.FloatField(default=0)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('student_name', models.CharField(max_length=200, unique=True)),
                ('monday_start', models.TimeField(blank=True, null=True, verbose_name='monday start')),
                ('monday_end', models.TimeField(blank=True, null=True, verbose_name='monday end')),
                ('monday_duration', models.FloatField(default=0)),
                ('tuesday_start', models.TimeField(blank=True, null=True, verbose_name='tuesday start')),
                ('tuesday_end', models.TimeField(blank=True, null=True, verbose_name='tuesday end')),
                ('tuesday_duration', models.FloatField(default=0)),
                ('wednesday_start', models.TimeField(blank=True, null=True, verbose_name='wednesday start')),
                ('wednesday_end', models.TimeField(blank=True, null=True, verbose_name='wednesday end')),
                ('wednesday_duration', models.FloatField(default=0)),
                ('thursday_start', models.TimeField(blank=True, null=True, verbose_name='thursday start')),
                ('thursday_end', models.TimeField(blank=True, null=True, verbose_name='thursday end')),
                ('thursday_duration', models.FloatField(default=0)),
                ('friday_start', models.TimeField(blank=True, null=True, verbose_name='friday start')),
                ('friday_end', models.TimeField(blank=True, null=True, verbose_name='friday end')),
                ('friday_duration', models.FloatField(default=0)),
                ('saturday_start', models.TimeField(blank=True, null=True, verbose_name='saturday start')),
                ('saturday_end', models.TimeField(blank=True, null=True, verbose_name='saturday end')),
                ('saturday_duration', models.FloatField(default=0)),
                ('sunday_start', models.TimeField(blank=True, null=True, verbose_name='sunday start')),
                ('sunday_end', models.TimeField(blank=True, null=True, verbose_name='sunday end')),
                ('sunday_duration', models.FloatField(default=0)),
                ('skill_1', models.BooleanField(default=False, verbose_name='ACT English')),
                ('skill_2', models.BooleanField(default=False, verbose_name='ACT Math')),
                ('skill_3', models.BooleanField(default=False, verbose_name='ACT Reading')),
                ('skill_4', models.BooleanField(default=False, verbose_name='ACT Science')),
                ('skill_5', models.BooleanField(default=False, verbose_name='ACT Writing')),
                ('skill_6', models.BooleanField(default=False, verbose_name='Floor ELA')),
                ('skill_7', models.BooleanField(default=False, verbose_name='Floor Math')),
                ('skill_8', models.BooleanField(default=False, verbose_name='Pre-Calculus')),
                ('skill_9', models.BooleanField(default=False, verbose_name='Calculus')),
                ('skill_10', models.BooleanField(default=False, verbose_name='Biology')),
                ('skill_11', models.BooleanField(default=False, verbose_name='Chemistry')),
                ('skill_12', models.BooleanField(default=False, verbose_name='Physics')),
                ('skill_13', models.BooleanField(default=False, verbose_name='Earth/Space')),
                ('skill_14', models.BooleanField(default=False, verbose_name='History')),
                ('skill_15', models.BooleanField(default=False, verbose_name='Spanish')),
                ('preferred_teacher1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred1', to='scheduler.Teacher')),
                ('preferred_teacher2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred2', to='scheduler.Teacher')),
                ('preferred_teacher3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred3', to='scheduler.Teacher')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('rejected_teacher1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejected1', to='scheduler.Teacher')),
                ('rejected_teacher2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejected2', to='scheduler.Teacher')),
                ('rejected_teacher3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejected3', to='scheduler.Teacher')),
                ('scheduled_hours', models.FloatField(blank=True, null=True, verbose_name='scheduled hours')),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='start datetime')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('nickname', models.CharField(max_length=200, unique=True)),
                ('monday_start', models.TimeField(blank=True, null=True, verbose_name='monday start')),
                ('monday_end', models.TimeField(blank=True, null=True, verbose_name='monday end')),
                ('monday_duration', models.FloatField(default=0)),
                ('tuesday_start', models.TimeField(blank=True, null=True, verbose_name='tuesday start')),
                ('tuesday_end', models.TimeField(blank=True, null=True, verbose_name='tuesday end')),
                ('tuesday_duration', models.FloatField(default=0)),
                ('wednesday_start', models.TimeField(blank=True, null=True, verbose_name='wednesday start')),
                ('wednesday_end', models.TimeField(blank=True, null=True, verbose_name='wednesday end')),
                ('wednesday_duration', models.FloatField(default=0)),
                ('thursday_start', models.TimeField(blank=True, null=True, verbose_name='thursday start')),
                ('thursday_end', models.TimeField(blank=True, null=True, verbose_name='thursday end')),
                ('thursday_duration', models.FloatField(default=0)),
                ('friday_start', models.TimeField(blank=True, null=True, verbose_name='friday start')),
                ('friday_end', models.TimeField(blank=True, null=True, verbose_name='friday end')),
                ('friday_duration', models.FloatField(default=0)),
                ('saturday_start', models.TimeField(blank=True, null=True, verbose_name='saturday start')),
                ('saturday_end', models.TimeField(blank=True, null=True, verbose_name='saturday end')),
                ('saturday_duration', models.FloatField(default=0)),
                ('sunday_start', models.TimeField(blank=True, null=True, verbose_name='sunday start')),
                ('sunday_end', models.TimeField(blank=True, null=True, verbose_name='sunday end')),
                ('sunday_duration', models.FloatField(default=0)),
                ('skill_1', models.BooleanField(default=False, verbose_name='ACT English')),
                ('skill_2', models.BooleanField(default=False, verbose_name='ACT Math')),
                ('skill_3', models.BooleanField(default=False, verbose_name='ACT Reading')),
                ('skill_4', models.BooleanField(default=False, verbose_name='ACT Science')),
                ('skill_5', models.BooleanField(default=False, verbose_name='ACT Writing')),
                ('skill_6', models.BooleanField(default=False, verbose_name='Floor ELA')),
                ('skill_7', models.BooleanField(default=False, verbose_name='Floor Math')),
                ('skill_8', models.BooleanField(default=False, verbose_name='Pre-Calculus')),
                ('skill_9', models.BooleanField(default=False, verbose_name='Calculus')),
                ('skill_10', models.BooleanField(default=False, verbose_name='Biology')),
                ('skill_11', models.BooleanField(default=False, verbose_name='Chemistry')),
                ('skill_12', models.BooleanField(default=False, verbose_name='Physics')),
                ('skill_13', models.BooleanField(default=False, verbose_name='Earth/Space')),
                ('skill_14', models.BooleanField(default=False, verbose_name='History')),
                ('skill_15', models.BooleanField(default=False, verbose_name='Spanish')),
                ('teacher_id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Student'),
        ),
        migrations.AddField(
            model_name='event',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Teacher'),
        ),

    ]
