# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(verbose_name='start datetime')),
                ('duration', models.FloatField(default=0)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=200, unique=True)),
                ('monday_start', models.DateTimeField(verbose_name='monday start')),
                ('monday_end', models.DateTimeField(verbose_name='monday end')),
                ('monday_duration', models.FloatField(default=0)),
                ('tuesday_start', models.DateTimeField(verbose_name='tuesday start')),
                ('tuesday_end', models.DateTimeField(verbose_name='tuesday end')),
                ('tuesday_duration', models.FloatField(default=0)),
                ('wednesday_start', models.DateTimeField(verbose_name='wednesday start')),
                ('wednesday_end', models.DateTimeField(verbose_name='wednesday end')),
                ('wednesday_duration', models.FloatField(default=0)),
                ('thursday_start', models.DateTimeField(verbose_name='thursday start')),
                ('thursday_end', models.DateTimeField(verbose_name='thursday end')),
                ('thursday_duration', models.FloatField(default=0)),
                ('friday_start', models.DateTimeField(verbose_name='friday start')),
                ('friday_end', models.DateTimeField(verbose_name='friday end')),
                ('friday_duration', models.FloatField(default=0)),
                ('saturday_start', models.DateTimeField(verbose_name='saturday start')),
                ('saturday_end', models.DateTimeField(verbose_name='saturday end')),
                ('saturday_duration', models.FloatField(default=0)),
                ('sunday_start', models.DateTimeField(verbose_name='sunday start')),
                ('sunday_end', models.DateTimeField(verbose_name='sunday end')),
                ('sunday_duration', models.FloatField(default=0)),
                ('skill_1', models.BooleanField()),
                ('skill_2', models.BooleanField()),
                ('skill_3', models.BooleanField()),
                ('skill_4', models.BooleanField()),
                ('skill_5', models.BooleanField()),
                ('skill_6', models.BooleanField()),
                ('skill_7', models.BooleanField()),
                ('skill_8', models.BooleanField()),
                ('skill_9', models.BooleanField()),
                ('skill_10', models.BooleanField()),
                ('skill_11', models.BooleanField()),
                ('skill_12', models.BooleanField()),
                ('skill_13', models.BooleanField()),
                ('skill_14', models.BooleanField()),
                ('skill_15', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('monday_start', models.DateTimeField(verbose_name='monday start')),
                ('monday_end', models.DateTimeField(verbose_name='monday end')),
                ('monday_duration', models.FloatField(default=0)),
                ('tuesday_start', models.DateTimeField(verbose_name='tuesday start')),
                ('tuesday_end', models.DateTimeField(verbose_name='tuesday end')),
                ('tuesday_duration', models.FloatField(default=0)),
                ('wednesday_start', models.DateTimeField(verbose_name='wednesday start')),
                ('wednesday_end', models.DateTimeField(verbose_name='wednesday end')),
                ('wednesday_duration', models.FloatField(default=0)),
                ('thursday_start', models.DateTimeField(verbose_name='thursday start')),
                ('thursday_end', models.DateTimeField(verbose_name='thursday end')),
                ('thursday_duration', models.FloatField(default=0)),
                ('friday_start', models.DateTimeField(verbose_name='friday start')),
                ('friday_end', models.DateTimeField(verbose_name='friday end')),
                ('friday_duration', models.FloatField(default=0)),
                ('saturday_start', models.DateTimeField(verbose_name='saturday start')),
                ('saturday_end', models.DateTimeField(verbose_name='saturday end')),
                ('saturday_duration', models.FloatField(default=0)),
                ('sunday_start', models.DateTimeField(verbose_name='sunday start')),
                ('sunday_end', models.DateTimeField(verbose_name='sunday end')),
                ('sunday_duration', models.FloatField(default=0)),
                ('skill_1', models.BooleanField()),
                ('skill_2', models.BooleanField()),
                ('skill_3', models.BooleanField()),
                ('skill_4', models.BooleanField()),
                ('skill_5', models.BooleanField()),
                ('skill_6', models.BooleanField()),
                ('skill_7', models.BooleanField()),
                ('skill_8', models.BooleanField()),
                ('skill_9', models.BooleanField()),
                ('skill_10', models.BooleanField()),
                ('skill_11', models.BooleanField()),
                ('skill_12', models.BooleanField()),
                ('skill_13', models.BooleanField()),
                ('skill_14', models.BooleanField()),
                ('skill_15', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_teacher1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred1', to='scheduler.User'),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_teacher2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred2', to='scheduler.User'),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_teacher3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred3', to='scheduler.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Student'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.User'),
        ),
    ]
