# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('duration', models.FloatField(default=0)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('student_name', models.CharField(max_length=200, unique=True)),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='start datetime')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('scheduled_hours', models.FloatField(blank=True, null=True, verbose_name='scheduled hours')),
                ('monday_start', models.TimeField(blank=True, null=True, verbose_name='monday start')),
                ('monday_end', models.TimeField(blank=True, null=True, verbose_name='monday end')),
                ('monday_duration', models.FloatField(default=0)),
                ('tuesday_start', models.TimeField(blank=True, null=True, verbose_name='tuesday start')),
                ('tuesday_end', models.TimeField(blank=True, null=True, verbose_name='tuesday end')),
                ('tuesday_duration', models.FloatField(default=0)),
                ('wednesday_start', models.TimeField(blank=True, null=True, verbose_name='wednesday start')),
                ('wednesday_end', models.TimeField(blank=True, null=True, verbose_name='wednesday end')),
                ('wednesday_duration', models.FloatField(default=0)),
                ('thursday_start', models.TimeField(blank=True, null=True, verbose_name='thursday start')),
                ('thursday_end', models.TimeField(blank=True, null=True, verbose_name='thursday end')),
                ('thursday_duration', models.FloatField(default=0)),
                ('friday_start', models.TimeField(blank=True, null=True, verbose_name='friday start')),
                ('friday_end', models.TimeField(blank=True, null=True, verbose_name='friday end')),
                ('friday_duration', models.FloatField(default=0)),
                ('saturday_start', models.TimeField(blank=True, null=True, verbose_name='saturday start')),
                ('saturday_end', models.TimeField(blank=True, null=True, verbose_name='saturday end')),
                ('saturday_duration', models.FloatField(default=0)),
                ('sunday_start', models.TimeField(blank=True, null=True, verbose_name='sunday start')),
                ('sunday_end', models.TimeField(blank=True, null=True, verbose_name='sunday end')),
                ('sunday_duration', models.FloatField(default=0)),
                ('skill_1', models.BooleanField(default=False, verbose_name='ACT English')),
                ('skill_2', models.BooleanField(default=False, verbose_name='ACT Math')),
                ('skill_3', models.BooleanField(default=False, verbose_name='ACT Reading')),
                ('skill_4', models.BooleanField(default=False, verbose_name='ACT Science')),
                ('skill_5', models.BooleanField(default=False, verbose_name='ACT Writing')),
                ('skill_6', models.BooleanField(default=False, verbose_name='Floor ELA')),
                ('skill_7', models.BooleanField(default=False, verbose_name='Floor Math')),
                ('skill_8', models.BooleanField(default=False, verbose_name='Pre-Calculus')),
                ('skill_9', models.BooleanField(default=False, verbose_name='Calculus')),
                ('skill_10', models.BooleanField(default=False, verbose_name='Biology')),
                ('skill_11', models.BooleanField(default=False, verbose_name='Chemistry')),
                ('skill_12', models.BooleanField(default=False, verbose_name='Physics')),
                ('skill_13', models.BooleanField(default=False, verbose_name='Earth/Space')),
                ('skill_14', models.BooleanField(default=False, verbose_name='History')),
                ('skill_15', models.BooleanField(default=False, verbose_name='Spanish')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('nickname', models.CharField(max_length=200, unique=True)),
                ('monday_start', models.TimeField(blank=True, null=True, verbose_name='monday start')),
                ('monday_end', models.TimeField(blank=True, null=True, verbose_name='monday end')),
                ('monday_duration', models.FloatField(default=0)),
                ('tuesday_start', models.TimeField(blank=True, null=True, verbose_name='tuesday start')),
                ('tuesday_end', models.TimeField(blank=True, null=True, verbose_name='tuesday end')),
                ('tuesday_duration', models.FloatField(default=0)),
                ('wednesday_start', models.TimeField(blank=True, null=True, verbose_name='wednesday start')),
                ('wednesday_end', models.TimeField(blank=True, null=True, verbose_name='wednesday end')),
                ('wednesday_duration', models.FloatField(default=0)),
                ('thursday_start', models.TimeField(blank=True, null=True, verbose_name='thursday start')),
                ('thursday_end', models.TimeField(blank=True, null=True, verbose_name='thursday end')),
                ('thursday_duration', models.FloatField(default=0)),
                ('friday_start', models.TimeField(blank=True, null=True, verbose_name='friday start')),
                ('friday_end', models.TimeField(blank=True, null=True, verbose_name='friday end')),
                ('friday_duration', models.FloatField(default=0)),
                ('saturday_start', models.TimeField(blank=True, null=True, verbose_name='saturday start')),
                ('saturday_end', models.TimeField(blank=True, null=True, verbose_name='saturday end')),
                ('saturday_duration', models.FloatField(default=0)),
                ('sunday_start', models.TimeField(blank=True, null=True, verbose_name='sunday start')),
                ('sunday_end', models.TimeField(blank=True, null=True, verbose_name='sunday end')),
                ('sunday_duration', models.FloatField(default=0)),
                ('skill_1', models.BooleanField(default=False, verbose_name='ACT English')),
                ('skill_2', models.BooleanField(default=False, verbose_name='ACT Math')),
                ('skill_3', models.BooleanField(default=False, verbose_name='ACT Reading')),
                ('skill_4', models.BooleanField(default=False, verbose_name='ACT Science')),
                ('skill_5', models.BooleanField(default=False, verbose_name='ACT Writing')),
                ('skill_6', models.BooleanField(default=False, verbose_name='Floor ELA')),
                ('skill_7', models.BooleanField(default=False, verbose_name='Floor Math')),
                ('skill_8', models.BooleanField(default=False, verbose_name='Pre-Calculus')),
                ('skill_9', models.BooleanField(default=False, verbose_name='Calculus')),
                ('skill_10', models.BooleanField(default=False, verbose_name='Biology')),
                ('skill_11', models.BooleanField(default=False, verbose_name='Chemistry')),
                ('skill_12', models.BooleanField(default=False, verbose_name='Physics')),
                ('skill_13', models.BooleanField(default=False, verbose_name='Earth/Space')),
                ('skill_14', models.BooleanField(default=False, verbose_name='History')),
                ('skill_15', models.BooleanField(default=False, verbose_name='Spanish')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_teacher1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred1', to='scheduler.Teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_teacher2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred2', to='scheduler.Teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_teacher3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred3', to='scheduler.Teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='rejected_teacher1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejected1', to='scheduler.Teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='rejected_teacher2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejected2', to='scheduler.Teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='rejected_teacher3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejected3', to='scheduler.Teacher'),
        ),
        migrations.AddField(
            model_name='event',
            name='student',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Student'),
        ),
        migrations.AddField(
            model_name='event',
            name='teacher',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Teacher'),
        ),
    ]
