# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20160507_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='skill_1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skill_10',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skill_11',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skill_12',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skill_13',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skill_14',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skill_15',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skill_2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skill_3',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skill_4',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skill_5',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skill_6',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skill_7',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skill_8',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skill_9',
        ),
        migrations.AddField(
            model_name='event',
            name='skill_1',
            field=models.BooleanField(default=False, verbose_name='ACT English'),
        ),
        migrations.AddField(
            model_name='event',
            name='skill_10',
            field=models.BooleanField(default=False, verbose_name='Biology'),
        ),
        migrations.AddField(
            model_name='event',
            name='skill_11',
            field=models.BooleanField(default=False, verbose_name='Chemistry'),
        ),
        migrations.AddField(
            model_name='event',
            name='skill_12',
            field=models.BooleanField(default=False, verbose_name='Physics'),
        ),
        migrations.AddField(
            model_name='event',
            name='skill_13',
            field=models.BooleanField(default=False, verbose_name='Earth/Space'),
        ),
        migrations.AddField(
            model_name='event',
            name='skill_14',
            field=models.BooleanField(default=False, verbose_name='History'),
        ),
        migrations.AddField(
            model_name='event',
            name='skill_15',
            field=models.BooleanField(default=False, verbose_name='Spanish'),
        ),
        migrations.AddField(
            model_name='event',
            name='skill_2',
            field=models.BooleanField(default=False, verbose_name='ACT Math'),
        ),
        migrations.AddField(
            model_name='event',
            name='skill_3',
            field=models.BooleanField(default=False, verbose_name='ACT Reading'),
        ),
        migrations.AddField(
            model_name='event',
            name='skill_4',
            field=models.BooleanField(default=False, verbose_name='ACT Science'),
        ),
        migrations.AddField(
            model_name='event',
            name='skill_5',
            field=models.BooleanField(default=False, verbose_name='ACT Writing'),
        ),
        migrations.AddField(
            model_name='event',
            name='skill_6',
            field=models.BooleanField(default=False, verbose_name='Floor ELA'),
        ),
        migrations.AddField(
            model_name='event',
            name='skill_7',
            field=models.BooleanField(default=False, verbose_name='Floor Math'),
        ),
        migrations.AddField(
            model_name='event',
            name='skill_8',
            field=models.BooleanField(default=False, verbose_name='Pre-Calculus'),
        ),
        migrations.AddField(
            model_name='event',
            name='skill_9',
            field=models.BooleanField(default=False, verbose_name='Calculus'),
        ),
    ]
