# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 02:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20160423_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.TimeField(verbose_name='start datetime'),
        ),
        migrations.AlterField(
            model_name='student',
            name='friday_end',
            field=models.TimeField(default=datetime.time(20, 47, 6, 362000), verbose_name='friday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='friday_start',
            field=models.TimeField(default=datetime.time(20, 47, 6, 362000), verbose_name='friday start'),
        ),
        migrations.AlterField(
            model_name='student',
            name='monday_end',
            field=models.TimeField(default=datetime.time(20, 47, 6, 362000), verbose_name='monday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='monday_start',
            field=models.TimeField(default=datetime.time(20, 47, 6, 362000), verbose_name='monday start'),
        ),
        migrations.AlterField(
            model_name='student',
            name='saturday_end',
            field=models.TimeField(default=datetime.time(20, 47, 6, 362000), verbose_name='saturday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='saturday_start',
            field=models.TimeField(default=datetime.time(20, 47, 6, 362000), verbose_name='saturday start'),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_10',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_11',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_12',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_13',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_14',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_15',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_6',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_8',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_9',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='sunday_end',
            field=models.TimeField(default=datetime.time(20, 47, 6, 363000), verbose_name='sunday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sunday_start',
            field=models.TimeField(default=datetime.time(20, 47, 6, 363000), verbose_name='sunday start'),
        ),
        migrations.AlterField(
            model_name='student',
            name='thursday_end',
            field=models.TimeField(default=datetime.time(20, 47, 6, 362000), verbose_name='thursday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='thursday_start',
            field=models.TimeField(default=datetime.time(20, 47, 6, 362000), verbose_name='thursday start'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tuesday_end',
            field=models.TimeField(default=datetime.time(20, 47, 6, 362000), verbose_name='tuesday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tuesday_start',
            field=models.TimeField(default=datetime.time(20, 47, 6, 362000), verbose_name='tuesday start'),
        ),
        migrations.AlterField(
            model_name='student',
            name='wednesday_end',
            field=models.TimeField(default=datetime.time(20, 47, 6, 362000), verbose_name='wednesday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='wednesday_start',
            field=models.TimeField(default=datetime.time(20, 47, 6, 362000), verbose_name='wednesday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friday_end',
            field=models.TimeField(default=datetime.time(20, 47, 6, 320000), verbose_name='friday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friday_start',
            field=models.TimeField(default=datetime.time(20, 47, 6, 320000), verbose_name='friday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='monday_end',
            field=models.TimeField(default=datetime.time(20, 47, 6, 319000), verbose_name='monday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='monday_start',
            field=models.TimeField(default=datetime.time(20, 47, 6, 319000), verbose_name='monday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saturday_end',
            field=models.TimeField(default=datetime.time(20, 47, 6, 320000), verbose_name='saturday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saturday_start',
            field=models.TimeField(default=datetime.time(20, 47, 6, 320000), verbose_name='saturday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sunday_end',
            field=models.TimeField(default=datetime.time(20, 47, 6, 320000), verbose_name='sunday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sunday_start',
            field=models.TimeField(default=datetime.time(20, 47, 6, 320000), verbose_name='sunday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='thursday_end',
            field=models.TimeField(default=datetime.time(20, 47, 6, 320000), verbose_name='thursday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='thursday_start',
            field=models.TimeField(default=datetime.time(20, 47, 6, 320000), verbose_name='thursday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tuesday_end',
            field=models.TimeField(default=datetime.time(20, 47, 6, 319000), verbose_name='tuesday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tuesday_start',
            field=models.TimeField(default=datetime.time(20, 47, 6, 319000), verbose_name='tuesday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wednesday_end',
            field=models.TimeField(default=datetime.time(20, 47, 6, 320000), verbose_name='wednesday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wednesday_start',
            field=models.TimeField(default=datetime.time(20, 47, 6, 319000), verbose_name='wednesday start'),
        ),
    ]
