# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20160507_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_start', models.TimeField(blank=True, null=True, verbose_name='monday start')),
                ('monday_end', models.TimeField(blank=True, null=True, verbose_name='monday end')),
                ('monday_duration', models.FloatField(default=0)),
                ('tuesday_start', models.TimeField(blank=True, null=True, verbose_name='tuesday start')),
                ('tuesday_end', models.TimeField(blank=True, null=True, verbose_name='tuesday end')),
                ('tuesday_duration', models.FloatField(default=0)),
                ('wednesday_start', models.TimeField(blank=True, null=True, verbose_name='wednesday start')),
                ('wednesday_end', models.TimeField(blank=True, null=True, verbose_name='wednesday end')),
                ('wednesday_duration', models.FloatField(default=0)),
                ('thursday_start', models.TimeField(blank=True, null=True, verbose_name='thursday start')),
                ('thursday_end', models.TimeField(blank=True, null=True, verbose_name='thursday end')),
                ('thursday_duration', models.FloatField(default=0)),
                ('friday_start', models.TimeField(blank=True, null=True, verbose_name='friday start')),
                ('friday_end', models.TimeField(blank=True, null=True, verbose_name='friday end')),
                ('friday_duration', models.FloatField(default=0)),
                ('saturday_start', models.TimeField(blank=True, null=True, verbose_name='saturday start')),
                ('saturday_end', models.TimeField(blank=True, null=True, verbose_name='saturday end')),
                ('saturday_duration', models.FloatField(default=0)),
                ('sunday_start', models.TimeField(blank=True, null=True, verbose_name='sunday start')),
                ('sunday_end', models.TimeField(blank=True, null=True, verbose_name='sunday end')),
                ('sunday_duration', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_1', models.BooleanField(default=False, verbose_name='ACT English')),
                ('skill_2', models.BooleanField(default=False, verbose_name='ACT Math')),
                ('skill_3', models.BooleanField(default=False, verbose_name='ACT Reading')),
                ('skill_4', models.BooleanField(default=False, verbose_name='ACT Science')),
                ('skill_5', models.BooleanField(default=False, verbose_name='ACT Writing')),
                ('skill_6', models.BooleanField(default=False, verbose_name='Floor ELA')),
                ('skill_7', models.BooleanField(default=False, verbose_name='Floor Math')),
                ('skill_8', models.BooleanField(default=False, verbose_name='Pre-Calculus')),
                ('skill_9', models.BooleanField(default=False, verbose_name='Calculus')),
                ('skill_10', models.BooleanField(default=False, verbose_name='Biology')),
                ('skill_11', models.BooleanField(default=False, verbose_name='Chemistry')),
                ('skill_12', models.BooleanField(default=False, verbose_name='Physics')),
                ('skill_13', models.BooleanField(default=False, verbose_name='Earth/Space')),
                ('skill_14', models.BooleanField(default=False, verbose_name='History')),
                ('skill_15', models.BooleanField(default=False, verbose_name='Spanish')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='skill_1',
        ),
        migrations.RemoveField(
            model_name='event',
            name='skill_10',
        ),
        migrations.RemoveField(
            model_name='event',
            name='skill_11',
        ),
        migrations.RemoveField(
            model_name='event',
            name='skill_12',
        ),
        migrations.RemoveField(
            model_name='event',
            name='skill_13',
        ),
        migrations.RemoveField(
            model_name='event',
            name='skill_14',
        ),
        migrations.RemoveField(
            model_name='event',
            name='skill_15',
        ),
        migrations.RemoveField(
            model_name='event',
            name='skill_2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='skill_3',
        ),
        migrations.RemoveField(
            model_name='event',
            name='skill_4',
        ),
        migrations.RemoveField(
            model_name='event',
            name='skill_5',
        ),
        migrations.RemoveField(
            model_name='event',
            name='skill_6',
        ),
        migrations.RemoveField(
            model_name='event',
            name='skill_7',
        ),
        migrations.RemoveField(
            model_name='event',
            name='skill_8',
        ),
        migrations.RemoveField(
            model_name='event',
            name='skill_9',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='friday_duration',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='friday_end',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='friday_start',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='monday_duration',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='monday_end',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='monday_start',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='saturday_duration',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='saturday_end',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='saturday_start',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='skill_1',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='skill_10',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='skill_11',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='skill_12',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='skill_13',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='skill_14',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='skill_15',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='skill_2',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='skill_3',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='skill_4',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='skill_5',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='skill_6',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='skill_7',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='skill_8',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='skill_9',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='sunday_duration',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='sunday_end',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='sunday_start',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='thursday_duration',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='thursday_end',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='thursday_start',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='tuesday_duration',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='tuesday_end',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='tuesday_start',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='wednesday_duration',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='wednesday_end',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='wednesday_start',
        ),
        migrations.AddField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='skills',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Event'),
        ),
        migrations.AddField(
            model_name='skills',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Teacher'),
        ),
        migrations.AddField(
            model_name='availability',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Teacher'),
        ),
    ]
