# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20160510_1329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
