# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_credentialsmodel_flowmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dicty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KeyVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=240)),
                ('value', models.CharField(db_index=True, max_length=240)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Dicty')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='friday_duration',
        ),
        migrations.RemoveField(
            model_name='student',
            name='friday_end',
        ),
        migrations.RemoveField(
            model_name='student',
            name='friday_start',
        ),
        migrations.RemoveField(
            model_name='student',
            name='monday_duration',
        ),
        migrations.RemoveField(
            model_name='student',
            name='monday_end',
        ),
        migrations.RemoveField(
            model_name='student',
            name='monday_start',
        ),
        migrations.RemoveField(
            model_name='student',
            name='saturday_duration',
        ),
        migrations.RemoveField(
            model_name='student',
            name='saturday_end',
        ),
        migrations.RemoveField(
            model_name='student',
            name='saturday_start',
        ),
        migrations.RemoveField(
            model_name='student',
            name='scheduled_hours',
        ),
        migrations.RemoveField(
            model_name='student',
            name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sunday_duration',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sunday_end',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sunday_start',
        ),
        migrations.RemoveField(
            model_name='student',
            name='thursday_duration',
        ),
        migrations.RemoveField(
            model_name='student',
            name='thursday_end',
        ),
        migrations.RemoveField(
            model_name='student',
            name='thursday_start',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tuesday_duration',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tuesday_end',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tuesday_start',
        ),
        migrations.RemoveField(
            model_name='student',
            name='wednesday_duration',
        ),
        migrations.RemoveField(
            model_name='student',
            name='wednesday_end',
        ),
        migrations.RemoveField(
            model_name='student',
            name='wednesday_start',
        ),
    ]
