# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_auto_20160526_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyval',
            name='container',
        ),
        migrations.DeleteModel(
            name='Dicty',
        ),
        migrations.DeleteModel(
            name='KeyVal',
        ),
    ]
