# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 21:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_auto_20160425_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='friday_end',
            field=models.TimeField(default=datetime.time(15, 29, 29, 15000), verbose_name='friday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='friday_start',
            field=models.TimeField(default=datetime.time(15, 29, 29, 15000), verbose_name='friday start'),
        ),
        migrations.AlterField(
            model_name='student',
            name='monday_end',
            field=models.TimeField(default=datetime.time(15, 29, 29, 15000), verbose_name='monday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='monday_start',
            field=models.TimeField(default=datetime.time(15, 29, 29, 15000), verbose_name='monday start'),
        ),
        migrations.AlterField(
            model_name='student',
            name='saturday_end',
            field=models.TimeField(default=datetime.time(15, 29, 29, 15000), verbose_name='saturday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='saturday_start',
            field=models.TimeField(default=datetime.time(15, 29, 29, 15000), verbose_name='saturday start'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sunday_end',
            field=models.TimeField(default=datetime.time(15, 29, 29, 15000), verbose_name='sunday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sunday_start',
            field=models.TimeField(default=datetime.time(15, 29, 29, 15000), verbose_name='sunday start'),
        ),
        migrations.AlterField(
            model_name='student',
            name='thursday_end',
            field=models.TimeField(default=datetime.time(15, 29, 29, 15000), verbose_name='thursday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='thursday_start',
            field=models.TimeField(default=datetime.time(15, 29, 29, 15000), verbose_name='thursday start'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tuesday_end',
            field=models.TimeField(default=datetime.time(15, 29, 29, 15000), verbose_name='tuesday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tuesday_start',
            field=models.TimeField(default=datetime.time(15, 29, 29, 15000), verbose_name='tuesday start'),
        ),
        migrations.AlterField(
            model_name='student',
            name='wednesday_end',
            field=models.TimeField(default=datetime.time(15, 29, 29, 15000), verbose_name='wednesday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='wednesday_start',
            field=models.TimeField(default=datetime.time(15, 29, 29, 15000), verbose_name='wednesday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friday_end',
            field=models.TimeField(default=datetime.time(15, 29, 28, 717000), verbose_name='friday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friday_start',
            field=models.TimeField(default=datetime.time(15, 29, 28, 717000), verbose_name='friday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='monday_end',
            field=models.TimeField(default=datetime.time(15, 29, 28, 717000), verbose_name='monday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='monday_start',
            field=models.TimeField(default=datetime.time(15, 29, 28, 717000), verbose_name='monday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saturday_end',
            field=models.TimeField(default=datetime.time(15, 29, 28, 717000), verbose_name='saturday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saturday_start',
            field=models.TimeField(default=datetime.time(15, 29, 28, 717000), verbose_name='saturday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sunday_end',
            field=models.TimeField(default=datetime.time(15, 29, 28, 717000), verbose_name='sunday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sunday_start',
            field=models.TimeField(default=datetime.time(15, 29, 28, 717000), verbose_name='sunday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='thursday_end',
            field=models.TimeField(default=datetime.time(15, 29, 28, 717000), verbose_name='thursday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='thursday_start',
            field=models.TimeField(default=datetime.time(15, 29, 28, 717000), verbose_name='thursday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tuesday_end',
            field=models.TimeField(default=datetime.time(15, 29, 28, 717000), verbose_name='tuesday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tuesday_start',
            field=models.TimeField(default=datetime.time(15, 29, 28, 717000), verbose_name='tuesday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wednesday_end',
            field=models.TimeField(default=datetime.time(15, 29, 28, 717000), verbose_name='wednesday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wednesday_start',
            field=models.TimeField(default=datetime.time(15, 29, 28, 717000), verbose_name='wednesday start'),
        ),
    ]
