# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 16:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_auto_20160425_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2016, 4, 27), null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='student',
            name='rejected_teacher1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejected1', to='scheduler.User'),
        ),
        migrations.AddField(
            model_name='student',
            name='rejected_teacher2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejected2', to='scheduler.User'),
        ),
        migrations.AddField(
            model_name='student',
            name='rejected_teacher3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejected3', to='scheduler.User'),
        ),
        migrations.AddField(
            model_name='student',
            name='scheduled_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='scheduled hours'),
        ),
        migrations.AddField(
            model_name='student',
            name='start_date',
            field=models.DateField(default=datetime.date(2016, 4, 27), verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='friday_end',
            field=models.TimeField(default=datetime.time(10, 49, 27, 740000), verbose_name='friday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='friday_start',
            field=models.TimeField(default=datetime.time(10, 49, 27, 740000), verbose_name='friday start'),
        ),
        migrations.AlterField(
            model_name='student',
            name='monday_end',
            field=models.TimeField(default=datetime.time(10, 49, 27, 740000), verbose_name='monday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='monday_start',
            field=models.TimeField(default=datetime.time(10, 49, 27, 740000), verbose_name='monday start'),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_teacher1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred1', to='scheduler.User'),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_teacher2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred2', to='scheduler.User'),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_teacher3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred3', to='scheduler.User'),
        ),
        migrations.AlterField(
            model_name='student',
            name='saturday_end',
            field=models.TimeField(default=datetime.time(10, 49, 27, 740000), verbose_name='saturday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='saturday_start',
            field=models.TimeField(default=datetime.time(10, 49, 27, 740000), verbose_name='saturday start'),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_1',
            field=models.BooleanField(default=False, verbose_name='ACT English'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sunday_end',
            field=models.TimeField(default=datetime.time(10, 49, 27, 740000), verbose_name='sunday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sunday_start',
            field=models.TimeField(default=datetime.time(10, 49, 27, 740000), verbose_name='sunday start'),
        ),
        migrations.AlterField(
            model_name='student',
            name='thursday_end',
            field=models.TimeField(default=datetime.time(10, 49, 27, 740000), verbose_name='thursday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='thursday_start',
            field=models.TimeField(default=datetime.time(10, 49, 27, 740000), verbose_name='thursday start'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tuesday_end',
            field=models.TimeField(default=datetime.time(10, 49, 27, 740000), verbose_name='tuesday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tuesday_start',
            field=models.TimeField(default=datetime.time(10, 49, 27, 740000), verbose_name='tuesday start'),
        ),
        migrations.AlterField(
            model_name='student',
            name='wednesday_end',
            field=models.TimeField(default=datetime.time(10, 49, 27, 740000), verbose_name='wednesday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='wednesday_start',
            field=models.TimeField(default=datetime.time(10, 49, 27, 740000), verbose_name='wednesday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friday_end',
            field=models.TimeField(default=datetime.time(10, 49, 27, 700000), verbose_name='friday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friday_start',
            field=models.TimeField(default=datetime.time(10, 49, 27, 700000), verbose_name='friday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='monday_end',
            field=models.TimeField(default=datetime.time(10, 49, 27, 700000), verbose_name='monday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='monday_start',
            field=models.TimeField(default=datetime.time(10, 49, 27, 700000), verbose_name='monday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saturday_end',
            field=models.TimeField(default=datetime.time(10, 49, 27, 700000), verbose_name='saturday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saturday_start',
            field=models.TimeField(default=datetime.time(10, 49, 27, 700000), verbose_name='saturday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sunday_end',
            field=models.TimeField(default=datetime.time(10, 49, 27, 700000), verbose_name='sunday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sunday_start',
            field=models.TimeField(default=datetime.time(10, 49, 27, 700000), verbose_name='sunday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='thursday_end',
            field=models.TimeField(default=datetime.time(10, 49, 27, 700000), verbose_name='thursday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='thursday_start',
            field=models.TimeField(default=datetime.time(10, 49, 27, 700000), verbose_name='thursday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tuesday_end',
            field=models.TimeField(default=datetime.time(10, 49, 27, 700000), verbose_name='tuesday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tuesday_start',
            field=models.TimeField(default=datetime.time(10, 49, 27, 700000), verbose_name='tuesday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wednesday_end',
            field=models.TimeField(default=datetime.time(10, 49, 27, 700000), verbose_name='wednesday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wednesday_start',
            field=models.TimeField(default=datetime.time(10, 49, 27, 700000), verbose_name='wednesday start'),
        ),
    ]
