# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 17:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_auto_20160427_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='friday_end',
            field=models.TimeField(default=datetime.time(11, 4, 0, 777000), verbose_name='friday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='friday_start',
            field=models.TimeField(default=datetime.time(11, 4, 0, 777000), verbose_name='friday start'),
        ),
        migrations.AlterField(
            model_name='student',
            name='monday_end',
            field=models.TimeField(default=datetime.time(11, 4, 0, 777000), verbose_name='monday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='monday_start',
            field=models.TimeField(default=datetime.time(11, 4, 0, 777000), verbose_name='monday start'),
        ),
        migrations.AlterField(
            model_name='student',
            name='saturday_end',
            field=models.TimeField(default=datetime.time(11, 4, 0, 777000), verbose_name='saturday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='saturday_start',
            field=models.TimeField(default=datetime.time(11, 4, 0, 777000), verbose_name='saturday start'),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_10',
            field=models.BooleanField(default=False, verbose_name='Biology'),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_11',
            field=models.BooleanField(default=False, verbose_name='Chemistry'),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_12',
            field=models.BooleanField(default=False, verbose_name='Physics'),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_13',
            field=models.BooleanField(default=False, verbose_name='Earth/Space'),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_14',
            field=models.BooleanField(default=False, verbose_name='History'),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_15',
            field=models.BooleanField(default=False, verbose_name='Spanish'),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_2',
            field=models.BooleanField(default=False, verbose_name='ACT Math'),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_3',
            field=models.BooleanField(default=False, verbose_name='ACT Reading'),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_4',
            field=models.BooleanField(default=False, verbose_name='ACT Science'),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_5',
            field=models.BooleanField(default=False, verbose_name='ACT Writing'),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_6',
            field=models.BooleanField(default=False, verbose_name='Floor ELA'),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_7',
            field=models.BooleanField(default=False, verbose_name='Floor Math'),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_8',
            field=models.BooleanField(default=False, verbose_name='Pre-Calculus'),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_9',
            field=models.BooleanField(default=False, verbose_name='Calculus'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sunday_end',
            field=models.TimeField(default=datetime.time(11, 4, 0, 777000), verbose_name='sunday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sunday_start',
            field=models.TimeField(default=datetime.time(11, 4, 0, 777000), verbose_name='sunday start'),
        ),
        migrations.AlterField(
            model_name='student',
            name='thursday_end',
            field=models.TimeField(default=datetime.time(11, 4, 0, 777000), verbose_name='thursday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='thursday_start',
            field=models.TimeField(default=datetime.time(11, 4, 0, 777000), verbose_name='thursday start'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tuesday_end',
            field=models.TimeField(default=datetime.time(11, 4, 0, 777000), verbose_name='tuesday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tuesday_start',
            field=models.TimeField(default=datetime.time(11, 4, 0, 777000), verbose_name='tuesday start'),
        ),
        migrations.AlterField(
            model_name='student',
            name='wednesday_end',
            field=models.TimeField(default=datetime.time(11, 4, 0, 777000), verbose_name='wednesday end'),
        ),
        migrations.AlterField(
            model_name='student',
            name='wednesday_start',
            field=models.TimeField(default=datetime.time(11, 4, 0, 777000), verbose_name='wednesday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friday_end',
            field=models.TimeField(default=datetime.time(11, 4, 0, 737000), verbose_name='friday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friday_start',
            field=models.TimeField(default=datetime.time(11, 4, 0, 737000), verbose_name='friday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='monday_end',
            field=models.TimeField(default=datetime.time(11, 4, 0, 737000), verbose_name='monday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='monday_start',
            field=models.TimeField(default=datetime.time(11, 4, 0, 737000), verbose_name='monday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saturday_end',
            field=models.TimeField(default=datetime.time(11, 4, 0, 737000), verbose_name='saturday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saturday_start',
            field=models.TimeField(default=datetime.time(11, 4, 0, 737000), verbose_name='saturday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill_1',
            field=models.BooleanField(default=False, verbose_name='ACT English'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill_10',
            field=models.BooleanField(default=False, verbose_name='Biology'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill_11',
            field=models.BooleanField(default=False, verbose_name='Chemistry'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill_12',
            field=models.BooleanField(default=False, verbose_name='Physics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill_13',
            field=models.BooleanField(default=False, verbose_name='Earth/Space'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill_14',
            field=models.BooleanField(default=False, verbose_name='History'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill_15',
            field=models.BooleanField(default=False, verbose_name='Spanish'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill_2',
            field=models.BooleanField(default=False, verbose_name='ACT Math'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill_3',
            field=models.BooleanField(default=False, verbose_name='ACT Reading'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill_4',
            field=models.BooleanField(default=False, verbose_name='ACT Science'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill_5',
            field=models.BooleanField(default=False, verbose_name='ACT Writing'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill_6',
            field=models.BooleanField(default=False, verbose_name='Floor ELA'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill_7',
            field=models.BooleanField(default=False, verbose_name='Floor Math'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill_8',
            field=models.BooleanField(default=False, verbose_name='Pre-Calculus'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill_9',
            field=models.BooleanField(default=False, verbose_name='Calculus'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sunday_end',
            field=models.TimeField(default=datetime.time(11, 4, 0, 737000), verbose_name='sunday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sunday_start',
            field=models.TimeField(default=datetime.time(11, 4, 0, 737000), verbose_name='sunday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='thursday_end',
            field=models.TimeField(default=datetime.time(11, 4, 0, 737000), verbose_name='thursday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='thursday_start',
            field=models.TimeField(default=datetime.time(11, 4, 0, 737000), verbose_name='thursday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tuesday_end',
            field=models.TimeField(default=datetime.time(11, 4, 0, 737000), verbose_name='tuesday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tuesday_start',
            field=models.TimeField(default=datetime.time(11, 4, 0, 737000), verbose_name='tuesday start'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wednesday_end',
            field=models.TimeField(default=datetime.time(11, 4, 0, 737000), verbose_name='wednesday end'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wednesday_start',
            field=models.TimeField(default=datetime.time(11, 4, 0, 737000), verbose_name='wednesday start'),
        ),
    ]
