# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_auto_20160427_1111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Teacher',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='teacher',
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.TimeField(verbose_name='Start Date'),
        ),
    ]
