# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 18:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_auto_20160427_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='password',
        ),
        migrations.AlterField(
            model_name='student',
            name='start_date',
            field=models.DateField(default=datetime.date(2016, 4, 28), verbose_name='start date'),
        ),
    ]
