# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_delete_clientsecret'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSecret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY', models.CharField(max_length=200)),
                ('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET', models.CharField(max_length=50)),
                ('SOCIAL_AUTH_GOOGLE_SCOPE1', models.TextField()),
                ('SOCIAL_AUTH_GOOGLE_SCOPE2', models.TextField()),
                ('SOCIAL_AUTH_LOGIN_REDIRECT_URL', models.CharField(max_length=50)),
                ('SOCIAL_AUTH_LOGIN_URL', models.CharField(max_length=50)),
            ],
        ),
    ]
