# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 23:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_auto_20160428_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='start_date',
            field=models.DateField(default=datetime.date(2016, 4, 30), verbose_name='start date'),
        ),
    ]
