# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_auto_20160430_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='start date'),
        ),
    ]
