# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 01:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0019_event_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 1, 1, 42, 31, 925000, tzinfo=utc), primary_key=True, serialize=False),
        ),
    ]
