# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0020_auto_20160430_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
