# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0023_remove_event_start_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
    ]
