# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0024_event_start_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='start_date',
        ),
        migrations.AddField(
            model_name='student',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start datetime'),
        ),
    ]
